apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: jenkins-pvc
spec:
  accessModes:
    - ReadWriteOnce
  volumeMode: Filesystem
  volumeName: jenkins-pv
  resources:
    requests:
      storage: 10Gi
  storageClassName: jenkins-pv
